### ISSUE TITLE
experimentos

### ISSUE THREAD

**Issue by Stigmind** [PinguinoIDE/pinguino-ide#103]
Traceback (most recent call last):
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\decorators.py", line 25, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\core.py", line 863, in pinguino_upload
    uploaded, result = self.pinguinoAPI.upload()
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\pinguino.py", line 137, in upload
    data = self.__upload__()
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\pinguino_tools.py", line 297, in __upload__
    result = self.upload_hex()
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\uploader\uploader.py", line 233, in upload_hex
    self.uploader.uploadDevice(self.hex_file, self.board)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\uploader\uploader8.py", line 624, in uploadDevice
    device_id, device_rev = self.getDeviceID(device, board)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\uploader\uploader8.py", line 300, in getDeviceID
    usbBuf = self.flashRead(device, 0x3FFFFE, 2)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\uploader\uploader8.py", line 354, in flashRead
    return self.sendCommand(device, usbBuf)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\uploader\uploader8.py", line 232, in sendCommand
    sent_bytes = self.usbWrite(device, usbBuf)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\uploader\uploader8.py", line 200, in usbWrite
    sent_bytes = device.write(self.OUT_EP, usbBuf, self.TIMEOUT)
  File "C:\Python27\lib\site-packages\usb\core.py", line 940, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "C:\Python27\lib\site-packages\usb\core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\usb\core.py", line 215, in setup_request
    intf, ep = self.get_interface_and_endpoint(device, endpoint_address)
  File "C:\Python27\lib\site-packages\usb\core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\usb\core.py", line 231, in get_interface_and_endpoint
    raise ValueError('Invalid endpoint address ' + hex(endpoint_address))
ValueError: Invalid endpoint address 0x1

os.name: nt
os.environ: {'TMP': 'C:\\Users\\Vidarr\\AppData\\Local\\Temp', 'COMPUTERNAME': 'BERSERKER', 'PROCESSOR_LEVEL': '6', 'PINGUINO_USER_PATH': 'C:\\Users\\Vidarr\\Documents\\Pinguino\\v12', 'USERDOMAIN': 'BERSERKER', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules', 'PINGUINO_NAME': 'Pinguino IDE', 'NO_XILINX_DATA_LICENSE': 'HIDDEN', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 78 Stepping 3, GenuineIntel', 'PROGRAMFILES': 'C:\\Program Files', 'PROCESSOR_REVISION': '4e03', 'PATH': 'C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Java\\jdk-9.0.4\\bin;C:\\Program Files (x86)\\Wolfram Research\\WolframScript\\;C:\\Program Files\\PuTTY\\;C:\\Program Files\\IVI Foundation\\VISA\\Win64\\Bin\\;C:\\Program Files (x86)\\IVI Foundation\\VISA\\WinNT\\Bin\\;C:\\Program Files (x86)\\IVI Foundation\\VISA\\WinNT\\Bin;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files (x86)\\Microchip\\xc8\\v2.05\\bin;C:\\Program Files\\MATLAB\\R2017b\\runtime\\win64;C:\\Program Files\\MATLAB\\R2017b\\bin;C:\\Users\\Vidarr\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\altera\\13.0sp1\\modelsim_ase\\win32aloem;C:\\Program Files\\Pinguino\\p8\\bin', 'SYSTEMROOT': 'C:\\WINDOWS', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'QUARTUS_ROOTDIR': 'C:\\altera\\13.0sp1\\quartus', 'TEMP': 'C:\\Users\\Vidarr\\AppData\\Local\\Temp', 'PINGUINO_OS_NAME': 'windows', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'PINGUINO_LIB': 'C:\\Program Files\\Pinguino\\v12\\pinguino', 'VXIPNPPATH': 'C:\\Program Files (x86)\\IVI Foundation\\VISA\\', 'PINGUINO_OS_ARCH': '64bit', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'PINGUINO_PYTHON': '2', 'LOCALAPPDATA': 'C:\\Users\\Vidarr\\AppData\\Local', 'HOMEPATH': '\\Users\\Vidarr', 'USERDOMAIN_ROAMINGPROFILE': 'BERSERKER', 'PINGUINO_VERSION': '12.0.39-beta.2', 'PROGRAMW6432': 'C:\\Program Files', 'USERNAME': 'Vidarr', 'PINGUINO_FULLNAME': 'Pinguino IDE 12.0.39-beta.2', 'SOPC_KIT_NIOS2': 'C:\\altera\\13.0sp1\\nios2eds', 'LOGONSERVER': '\\\\BERSERKER', 'PROMPT': '$P$G', 'SESSIONNAME': 'Console', 'NIEXTCCOMPILERSUPP': 'C:\\Program Files (x86)\\National Instruments\\Shared\\ExternalCompilerSupport\\C\\', 'PROGRAMDATA': 'C:\\ProgramData', 'ONEDRIVE': 'C:\\Users\\Vidarr\\OneDrive', 'PINGUINO_MODE': 'NORMAL', 'PUBLIC': 'C:\\Users\\Public', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'CONFIGSETROOT': 'C:\\WINDOWS\\ConfigSetRoot', 'PINGUINO_DEFAULT_FILES': 'C:\\Users\\Vidarr\\Documents\\Pinguino\\v12\\local', 'WINDIR': 'C:\\WINDOWS', 'APPDATA': 'C:\\Users\\Vidarr\\AppData\\Roaming', 'HOMEDRIVE': 'C:', 'PINGUINO_USERLIBS_PATH': 'C:\\Users\\Vidarr\\Documents\\Pinguino\\v12\\pinguinolibs', 'SYSTEMDRIVE': 'C:', 'PINGUINO_INSTALL_PATH': 'C:\\Program Files\\Pinguino\\v12\\', 'NUMBER_OF_PROCESSORS': '4', 'PINGUINO_PROJECT': '', 'PINGUINO_BOARD_ARCH': '8', 'VXIPNPPATH64': 'C:\\Program Files\\IVI Foundation\\VISA\\', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'OS': 'Windows_NT', 'ADSK_CLM_WPAD_PROXY_CHECK': 'FALSE', 'PINGUINO_CAN_COMPILE': 'True', 'USERPROFILE': 'C:\\Users\\Vidarr'}

**Comment by MefhigosetH** [comment]
Duplicate #108
