### ISSUE TITLE
Compilation not working

### ISSUE THREAD

**Issue by gopenelectronics** [PinguinoIDE/pinguino-ide#113]
Traceback (most recent call last):
  File "C:\Pinguino\V13_temp\pinguino-ide\pinguino\qtgui\ide\methods\decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "C:\Pinguino\V13_temp\pinguino-ide\pinguino\qtgui\ide\methods\decorators.py", line 25, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "C:\Pinguino\V13_temp\pinguino-ide\pinguino\qtgui\ide\methods\decorators.py", line 161, in wrapped
    if saved: fn(Pinguino, *args, **kwargs)
  File "C:\Pinguino\V13_temp\pinguino-ide\pinguino\qtgui\ide\methods\decorators.py", line 174, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "C:\Pinguino\V13_temp\pinguino-ide\pinguino\qtgui\ide\methods\core.py", line 786, in pinguino_compile
    compile_code()
  File "C:\Pinguino\V13_temp\pinguino-ide\pinguino\qtgui\ide\methods\core.py", line 765, in <lambda>
    compile_code = lambda :self.pinguinoAPI.compile_file([filename])
  File "C:\Pinguino\V13_temp\pinguino-ide\pinguino\qtgui\pinguino_core\pinguino.py", line 85, in compile_file
    data = self.verify(file_path)
  File "C:\Pinguino\V13_temp\pinguino-ide\pinguino\qtgui\pinguino_core\pinguino_tools.py", line 225, in verify
    self.set_os_variables()
  File "C:\Pinguino\V13_temp\pinguino-ide\pinguino\qtgui\pinguino_core\pinguino_tools.py", line 85, in set_os_variables
    self.COMPILER_8BIT = os.path.join(self.P8_XC8_BIN, "xc8.exe")  #change for xc8
AttributeError: 'Pinguino' object has no attribute 'P8_XC8_BIN'

**Comment by esternin** [comment]
Yes, I ran into these, too.  You need to download and install xc8 compiler separately, from [Microchip site](https://www.microchip.com/mplab/compilers), and supply the location of the xc8 executable in the .config file.

 See my log of installation in issue #114.
