### ISSUE TITLE
Unable to upload to a target board via USB 

### ISSUE THREAD

**Issue by esternin** [PinguinoIDE/pinguino-ide#114]
This is the first installation of Pinguino, no previous files.  The installation instructions were followed, but because they were incomplete, or confusing, I will summarize what I did below, hopefully this will help someone as well as explain exactly what my configuration is. None of the "automatic" installation scripts worked in my environment, which is a multi-user installation on a number of workstations, that have a network-mounted shared /opt. In addition, to all the PinguinoIDE stuff, I had to retrieve and install the compilers, and also add a reserved.pickle to the user space (this last thing after that space gets created by the first run of the ide python script, so **after** the inevitable crash at first startup of Pinguino.

In summary, this is what I did.  As myself:
```
mkdir /tmp/pinguino
cd /tmp/pinguino
git clone https://github.com/PinguinoIDE/pinguino-ide.git pinguino-ide
git clone https://github.com/PinguinoIDE/pinguino-libraries.git pinguino-libraries 
```
Also, download the MPLAB compilers, from `https://www.microchip.com/mplab/compilers`. They are packaged as self-installing scripts, `xc32-v2.30-full-install-linux-installer.run` and `xc8-v2.10-full-install-linux-installer.run`, so I `chmod 755` them ad execute them.  They install into `/opt/microchip/xc32` and `/opt/microship/xc8`.

I get the p8/p32 compilers from `https://codeload.github.com/PinguinoIDE/pinguino-compilers/zip/master`. I unpack everything in /tmp, then, as root, move everything into one common place I want them to be in, for example: 
```
sudo bash
mkdir -p /opt/pinguino/compilers
mv /tmp/pinguino-compilers-master/linux64/* /opt/pinguino/compilers
mv /tmp/Pinguino/v13 /opt/pinguino
chown -R root.root /opt/pinguino
```
I edit the two config filesto reflect this arrangement:
```
$ cat /opt/pinguino/v13/pinguino-ide/pinguino/paths.conf 
[paths-linux]
install_path = /opt/pinguino/v13
user_path = ~/Pinguino/v13

$ cat /opt/pinguino/v13/pinguino-ide/pinguino/qtgui/config/pinguino.linux.conf 
[Paths]
sdcc_bin = /opt/pinguino/compilers/p8/bin
gcc_bin  = /opt/pinguino/compilers/p32/bin
xc8_bin  = /opt/microchip/xc8/v2.10/bin
pinguino_8_libs = /opt/pinguino/v13/pinguino-libraries/p8
pinguino_32_libs = /opt/pinguino/v13/pinguino-libraries/p32
install_path = /opt/pinguino/v13/pinguino-ide

user_path = ~/Pinguino/v13
user_libs = ${user_path}/pinguinolibs
```
Still as root, I execute (once) the commands in `/opt/pinguino/v13/pinguino-ide/pinguino.sh`, except the last line that launches the IDE, to take care of all missing python bits: 
```
cd /opt/pinguino/v13/pinguino-ide
python3 -m pip install --upgrade pip pyside pyusb
python3 -m pip install --upgrade wheel beautifulsoup4 setuptools requests
python -m pip install --upgrade pybluez
```
Still as root, I add a rules file for the udev/USB recognition. 
```
$ cat /etc/udev/rules.d/82-pinguino.rules 
# PiC-32 Pinguino Micro
ATTRS{idVendor}=="04d8", ATTRS{idProduct}=="003c", SYMLINK+="pinguino%n", MODE="0666"
$ ls -la /dev/pinguino*
lrwxrwxrwx 1 root root 11 Jan 17 15:51 /dev/pinguino0 -> usb/hiddev0
lrwxrwxrwx 1 root root  7 Jan 17 15:51 /dev/pinguino2 -> hidraw2
lrwxrwxrwx 1 root root 15 Jan 17 15:51 /dev/pinguino3 -> bus/usb/001/037
$ lsusb -d 04d8:003C
Bus 001 Device 036: ID 04d8:003c Microchip Technology, Inc. 
```
so the board is recognized (as soon as I put it into the bootloader mode (by holding But and pressing and releasing Rst), and I also add a unique symbolic `/dev/pinguino*` link, just for fun, and it seems to be there and writeable by everyone.
 
Finally, as user:
```
python3 /opt/pinguino/v13/pinguino-ide/pinguino-ide.py
```
which creates the `~/Pinguino/v13` subdirectory, and copies example files in, but crashes because of a missing file, so I exit it, then
``` 
cd ~/Pinguino/v13
wget https://raw.githubusercontent.com/PinguinoIDE/pinguino-ide-tk/master/tkgui/config/reserved.pickle
```
and the next time everything works.

**Now** I can describe the actual issue. 

Compile works, the board selection works, tried with both PIC32 Pinguino Micro and PIC32 Pinguino OTG. Any attempt to Upload to the board, causes this error:
```
Traceback (most recent call last):
  File "/opt/pinguino/v13/pinguino-ide/pinguino/qtgui/ide/methods/decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "/opt/pinguino/v13/pinguino-ide/pinguino/qtgui/ide/methods/decorators.py", line 25, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "/opt/pinguino/v13/pinguino-ide/pinguino/qtgui/ide/methods/core.py", line 863, in pinguino_upload
    uploaded, result = self.pinguinoAPI.upload()
  File "/opt/pinguino/v13/pinguino-ide/pinguino/qtgui/pinguino_core/pinguino.py", line 137, in upload
    data = self.__upload__()
  File "/opt/pinguino/v13/pinguino-ide/pinguino/qtgui/pinguino_core/pinguino_tools.py", line 298, in __upload__
    result = self.upload_hex()
  File "/opt/pinguino/v13/pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader.py", line 233, in upload_hex
    self.uploader.uploadDevice(self.hex_file, self.board)
  File "/opt/pinguino/v13/pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader32.py", line 858, in uploadDevice
    handle = self.initDevice(device)
  File "/opt/pinguino/v13/pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader.py", line 175, in initDevice
    handle.setConfiguration(self.ACTIVE_CONFIG)
  File "/usr/local/lib/python3.6/site-packages/usb/legacy.py", line 260, in setConfiguration
    self.dev.set_configuration(configuration)
  File "/usr/local/lib/python3.6/site-packages/usb/core.py", line 869, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "/usr/local/lib/python3.6/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/usb/core.py", line 148, in managed_set_configuration
    self.backend.set_configuration(self.handle, cfg.bConfigurationValue)
  File "/usr/local/lib/python3.6/site-packages/usb/backend/libusb1.py", line 794, in set_configuration
    _check(self.lib.libusb_set_configuration(dev_handle.handle, config_value))
  File "/usr/local/lib/python3.6/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 16] Resource busy
```

I must be missing something small and stupid.  Any help would be greatly appreciated.

**Comment by esternin** [comment]
Here are some more details, this time from a run under python3:
```
[INFO] Welcome to Pinguino IDE 13.0.0

[INFO] Compiling: /home/esternin/Pinguino/v13/examples/01.Basics/Blink/Blink.pde
[INFO] Board: PIC32 Pinguino OTG
[INFO] Proc: 32MX440F256H
[INFO] Arch: 32
[INFO] MIPS 16: True
[INFO] Heap size: 512 bytes
[INFO] Optimization: -O2
[INFO] Bootloader: usb
[INFO] compilation done
[INFO] Code size: 1572/233472 bytes (0.67% used)
[INFO] 1.304 seconds process time
[INFO] Looking for a Pinguino device ...

[INFO] Pinguino found ...

[DEBUG] Traceback (most recent call last):
  File "/opt/pinguino/v13/pinguino-ide/pinguino/qtgui/ide/methods/decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "/opt/pinguino/v13/pinguino-ide/pinguino/qtgui/ide/methods/decorators.py", line 25, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "/opt/pinguino/v13/pinguino-ide/pinguino/qtgui/ide/methods/core.py", line 863, in pinguino_upload
    uploaded, result = self.pinguinoAPI.upload()
  File "/opt/pinguino/v13/pinguino-ide/pinguino/qtgui/pinguino_core/pinguino.py", line 137, in upload
    data = self.__upload__()
  File "/opt/pinguino/v13/pinguino-ide/pinguino/qtgui/pinguino_core/pinguino_tools.py", line 298, in __upload__
    result = self.upload_hex()
  File "/opt/pinguino/v13/pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader.py", line 233, in upload_hex
    self.uploader.uploadDevice(self.hex_file, self.board)
  File "/opt/pinguino/v13/pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader32.py", line 858, in uploadDevice
    handle = self.initDevice(device)
  File "/opt/pinguino/v13/pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader.py", line 175, in initDevice
    handle.setConfiguration(self.ACTIVE_CONFIG)
  File "/usr/local/lib/python3.6/site-packages/usb/legacy.py", line 260, in setConfiguration
    self.dev.set_configuration(configuration)
  File "/usr/local/lib/python3.6/site-packages/usb/core.py", line 869, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "/usr/local/lib/python3.6/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/usb/core.py", line 148, in managed_set_configuration
    self.backend.set_configuration(self.handle, cfg.bConfigurationValue)
  File "/usr/local/lib/python3.6/site-packages/usb/backend/libusb1.py", line 794, in set_configuration
    _check(self.lib.libusb_set_configuration(dev_handle.handle, config_value))
  File "/usr/local/lib/python3.6/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 16] Resource busy
```
Line 595 of `libusb1.py` is this:
```
# check a libusb function call
def _check(ret):
    if hasattr(ret, 'value'):
        ret = ret.value

    if ret < 0:
        if ret == LIBUSB_ERROR_NOT_SUPPORTED:
            raise NotImplementedError(_strerror(ret))
        else:
            raise USBError(_strerror(ret), ret, _libusb_errno[ret])

    return ret
```

It looks like a returned structure does not have an attribute named "value".

Any ideas, folks?

**Comment by MefhigosetH** [comment]
Dear @esternin ,

Thanks for your time to share this info with us.

I plan publish a manual install guide on the Pingüino Website, based on this issue.

Cheers.
