### ISSUE TITLE
Cannot upload to device 18F4550

### ISSUE THREAD

**Issue by luzemario** [PinguinoIDE/pinguino-ide#125]
Hi, folks

I am using bootloader firmware v4.14 18F4550 20MHz, since the external crystal is 20MHz. device was allowed by udev rules to be "666".

lsusb output:

```
Bus 001 Device 009: ID 04d8:feaa Microchip Technology, Inc. P8
```

dmesg:

```
[10634.172990] usb 1-3: new full-speed USB device number 9 using xhci_hcd
[10634.330780] usb 1-3: New USB device found, idVendor=04d8, idProduct=feaa, bcdDevice= 4.14
[10634.330785] usb 1-3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[10634.330788] usb 1-3: Product: P8
[10634.330790] usb 1-3: Manufacturer: RB+AG
```

Traceback:

```
Traceback (most recent call last):
  File "/home/luzemario/.pinguino/v13/pinguino-ide-fix-linux-support/pinguino/qtgui/pinguino_core/uploader/uploader.py", line 158, in initDevice
    device.set_configuration(self.ACTIVE_CONFIG)
  File "/home/luzemario/.local/share/virtualenvs/pinguino-ide-fix-linux-support-AeDf6_aL/lib/python3.8/site-packages/usb/core.py", line 903, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "/home/luzemario/.local/share/virtualenvs/pinguino-ide-fix-linux-support-AeDf6_aL/lib/python3.8/site-packages/usb/core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "/home/luzemario/.local/share/virtualenvs/pinguino-ide-fix-linux-support-AeDf6_aL/lib/python3.8/site-packages/usb/core.py", line 158, in managed_set_configuration
    self.managed_open()
  File "/home/luzemario/.local/share/virtualenvs/pinguino-ide-fix-linux-support-AeDf6_aL/lib/python3.8/site-packages/usb/core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "/home/luzemario/.local/share/virtualenvs/pinguino-ide-fix-linux-support-AeDf6_aL/lib/python3.8/site-packages/usb/core.py", line 131, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "/home/luzemario/.local/share/virtualenvs/pinguino-ide-fix-linux-support-AeDf6_aL/lib/python3.8/site-packages/usb/backend/libusb1.py", line 804, in open_device
    return _DeviceHandle(dev)
  File "/home/luzemario/.local/share/virtualenvs/pinguino-ide-fix-linux-support-AeDf6_aL/lib/python3.8/site-packages/usb/backend/libusb1.py", line 652, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "/home/luzemario/.local/share/virtualenvs/pinguino-ide-fix-linux-support-AeDf6_aL/lib/python3.8/site-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 5] Input/Output Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luzemario/.pinguino/v13/pinguino-ide-fix-linux-support/pinguino/qtgui/ide/methods/decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "/home/luzemario/.pinguino/v13/pinguino-ide-fix-linux-support/pinguino/qtgui/ide/methods/decorators.py", line 25, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "/home/luzemario/.pinguino/v13/pinguino-ide-fix-linux-support/pinguino/qtgui/ide/methods/core.py", line 863, in pinguino_upload
    uploaded, result = self.pinguinoAPI.upload()
  File "/home/luzemario/.pinguino/v13/pinguino-ide-fix-linux-support/pinguino/qtgui/pinguino_core/pinguino.py", line 137, in upload
    data = self.__upload__()
  File "/home/luzemario/.pinguino/v13/pinguino-ide-fix-linux-support/pinguino/qtgui/pinguino_core/pinguino_tools.py", line 298, in __upload__
    result = self.upload_hex()
  File "/home/luzemario/.pinguino/v13/pinguino-ide-fix-linux-support/pinguino/qtgui/pinguino_core/uploader/uploader.py", line 233, in upload_hex
    self.uploader.uploadDevice(self.hex_file, self.board)
  File "/home/luzemario/.pinguino/v13/pinguino-ide-fix-linux-support/pinguino/qtgui/pinguino_core/uploader/uploader8.py", line 620, in uploadDevice
    device = self.initDevice(device)
  File "/home/luzemario/.pinguino/v13/pinguino-ide-fix-linux-support/pinguino/qtgui/pinguino_core/uploader/uploader.py", line 160, in initDevice
    sys.exit("Could not set configuration: %s" % str(e))
SystemExit: Could not set configuration: [Errno 5] Input/Output Error
```

**Comment by luzemario** [comment]
I figured out that sometimes Pinguino shows a warning abou PIC not found, so I pressed reset and the upload was successful.

But I still cannot make sure if the program is running. There is no signs or user program running, not even the "blink" example. I checked pin by pin with a multimeter, and the is no voltage changes.
