### ISSUE TITLE
ImportError: No module named environ_viewer

### ISSUE THREAD

**Issue by rblanchot** [PinguinoIDE/pinguino-ide#28]
Traceback (most recent call last):
  File "./pinguino.py", line 144, in <module>
    from qtgui.ide.ide import PinguinoIDE
  File "/dvpt/pinguino/git-copy/pinguino-ide/qtgui/ide/ide.py", line 10, in <module>
    from .events.events import PinguinoEvents
  File "/dvpt/pinguino/git-copy/pinguino-ide/qtgui/ide/events/events.py", line 6, in <module>
    from .event_methods import EventMethods
  File "/dvpt/pinguino/git-copy/pinguino-ide/qtgui/ide/events/event_methods.py", line 36, in <module>
    from ..child_windows.environ_viewer import EnvironViewer
  File "/dvpt/pinguino/git-copy/pinguino-ide/qtgui/ide/child_windows/environ_viewer.py", line 9, in <module>
    from ...frames.environ_viewer import Ui_EnvironViewer
ImportError: No module named environ_viewer

**Comment by rblanchot** [comment]
Momentarily fixed by commenting line 9 in qtgui/ide/child_windows/environ_viewer.py :

#from ...frames.environ_viewer import Ui_EnvironViewer

**Comment by YeisonEng** [comment]
Fixed after add this file https://github.com/PinguinoIDE/pinguino-ide/blob/master/qtgui/frames/environ_viewer.py
