### ISSUE TITLE
Cannot load example files

### ISSUE THREAD

**Issue by rblanchot** [PinguinoIDE/pinguino-ide#43]
From jojo1964 (http://forum.pinguino.cc/showthread.php?tid=4561) :

Hi Guys,

I am new to pinguino and had a bad first experience.
I have installed the ide latest version (11.0 beta 3) on both a windows 7 32 bit and 64 bit system.

Both show the same problem. After installing without a hitch, I can only load an example file once.

When I try to load the same or other file in a later session nothing happens and the follwing error is show in the python window:

WARNING:root:pysvn is an optional dependence for Pinguino's Library Manager.
WARNING:root:hgapi is an optional dependence for Pinguino's Library Manager.
Pinguino IDE started!
Traceback (most recent call last):
File "C:\pinguino-11\qtgui\ide\events\event_methods.py", line 973, in jump_dir
_files
self.open_file_from_path(filename=getattr(list_widget_item, "path_file"))
File "C:\pinguino-11\qtgui\ide\methods\methods.py", line 37, in open_file_from
_path
self.new_file(filename=filename)
File "C:\pinguino-11\qtgui\ide\methods\decorators.py", line 232, in wrapped
return fn(Pinguino, _args, *_kwargs)
File "C:\pinguino-11\qtgui\ide\events\event_methods.py", line 49, in new_file
editor = PinguinoCodeEditor()
File "C:\pinguino-11\qtgui\ide\code_editor\pinguino_code_editor.py", line 27,
in __init__
self.text_edit = CustomTextEdit(self, self.line_number)
File "C:\pinguino-11\qtgui\ide\code_editor\editor.py", line 25, in **init**
self.completer = PinguinoAutoCompleter()
File "C:\pinguino-11\qtgui\ide\code_editor\autocompleter.py", line 62, in **in
it**
self.namespaces = pickle.load(file_reserved)
File "C:\Python27\lib\pickle.py", line 1378, in load
return Unpickler(file).load()
File "C:\Python27\lib\pickle.py", line 858, in load
dispatch[key](self)
File "C:\Python27\lib\pickle.py", line 966, in load_string
raise ValueError, "insecure string pickle"
ValueError: insecure string pickle

Any solution, did I do something wrong??

**Comment by rblanchot** [comment]
Removing the pickle files in the user directory seems to solve the problem.

**Comment by robertkendrick** [comment]
Thanks for this. I have exactly the same problem.
When you refer to the 'user directory' where exactly do you mean ?

**Comment by asm7100** [comment]
Hi I maby in here C:\pinguino-11\user
There is to files
reserved.pickle
and 
wikidocs.pickle
Maby it is this

**Comment by amabiles** [comment]
tengo problemas al instalar pinguino ide en debian buster me sale este error python: can't open file '/opt/pinguino/v12/pinguino-ide.py': [Errno 2] No such file or directory que hacer mil gracias por su tiempo

**Comment by MefhigosetH** [comment]
Resuelto.
