### ISSUE TITLE
Invalid endpoint address ' + hex(endpoint_address) Invalid endpoint address 0x1

### ISSUE THREAD

**Issue by lumaleo** [PinguinoIDE/pinguino-ide#80]
Traceback (most recent call last):
  File "D:\Programas\Pinguino\v12\pinguino\qtgui\ide\methods\decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "D:\Programas\Pinguino\v12\pinguino\qtgui\ide\methods\decorators.py", line 25, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "D:\Programas\Pinguino\v12\pinguino\qtgui\ide\methods\core.py", line 863, in pinguino_upload
    uploaded, result = self.pinguinoAPI.upload()
  File "D:\Programas\Pinguino\v12\pinguino\qtgui\pinguino_core\pinguino.py", line 137, in upload
    data = self.__upload__()
  File "D:\Programas\Pinguino\v12\pinguino\qtgui\pinguino_core\pinguino_tools.py", line 297, in __upload__
    result = self.upload_hex()
  File "D:\Programas\Pinguino\v12\pinguino\qtgui\pinguino_core\uploader\uploader.py", line 233, in upload_hex
    self.uploader.uploadDevice(self.hex_file, self.board)
  File "D:\Programas\Pinguino\v12\pinguino\qtgui\pinguino_core\uploader\uploader8.py", line 622, in uploadDevice
    device_id, device_rev = self.getDeviceID(device, board)
  File "D:\Programas\Pinguino\v12\pinguino\qtgui\pinguino_core\uploader\uploader8.py", line 298, in getDeviceID
    usbBuf = self.flashRead(device, 0x3FFFFE, 2)
  File "D:\Programas\Pinguino\v12\pinguino\qtgui\pinguino_core\uploader\uploader8.py", line 352, in flashRead
    return self.sendCommand(device, usbBuf)
  File "D:\Programas\Pinguino\v12\pinguino\qtgui\pinguino_core\uploader\uploader8.py", line 230, in sendCommand
    sent_bytes = self.usbWrite(device, usbBuf)
  File "D:\Programas\Pinguino\v12\pinguino\qtgui\pinguino_core\uploader\uploader8.py", line 200, in usbWrite
    sent_bytes = device.write(self.OUT_EP, usbBuf, self.TIMEOUT)
  File "D:\Programas\Python27\lib\site-packages\usb\core.py", line 940, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "D:\Programas\Python27\lib\site-packages\usb\core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "D:\Programas\Python27\lib\site-packages\usb\core.py", line 215, in setup_request
    intf, ep = self.get_interface_and_endpoint(device, endpoint_address)
  File "D:\Programas\Python27\lib\site-packages\usb\core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "D:\Programas\Python27\lib\site-packages\usb\core.py", line 231, in get_interface_and_endpoint
    raise ValueError('Invalid endpoint address ' + hex(endpoint_address))
ValueError: Invalid endpoint address 0x1

os.name: nt
os.environ: {'TMP': 'C:\\Users\\LUMALE~1\\AppData\\Local\\Temp', 'COMPUTERNAME': 'LUMALEO-PC', 'PINGUINO_USER_PATH': 'C:\\Users\\lumaleo-PC\\Documents\\Pinguino\\v12', 'USERDOMAIN': 'LUMALEO-PC', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules', 'PINGUINO_NAME': 'Pinguino IDE', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel', 'PROGRAMFILES': 'C:\\Program Files', 'PROCESSOR_REVISION': '3a09', 'SYSTEMROOT': 'C:\\WINDOWS', 'PATH': 'd:\\Programas\\Embarcadero\\Studio\\18.0\\bin;C:\\Users\\Public\\Documents\\Embarcadero\\Studio\\18.0\\Bpl;d:\\Programas\\Embarcadero\\Studio\\18.0\\bin64;C:\\Users\\Public\\Documents\\Embarcadero\\Studio\\18.0\\Bpl\\Win64;d:\\Programas\\Embarcadero\\Studio\\16.0\\bin;C:\\Users\\Public\\Documents\\Embarcadero\\Studio\\16.0\\Bpl;d:\\Programas\\Embarcadero\\Studio\\16.0\\bin64;C:\\Users\\Public\\Documents\\Embarcadero\\Studio\\16.0\\Bpl\\Win64;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;d:\\Programas\\MATLAB\\R2016b\\runtime\\win64;d:\\Programas\\MATLAB\\R2016b\\bin;d:\\Programas\\MATLAB\\R2016b\\polyspace\\bin;d:\\Programas\\Anaconda3;d:\\Programas\\Anaconda3\\Scripts;d:\\Programas\\Anaconda3\\Library\\bin;D:\\Programas\\PICC;C:\\Users\\lumaleo-PC\\AppData\\Local\\Microsoft\\WindowsApps;;d:\\Programas\\Pinguino\\p8\\bin', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'TEMP': 'C:\\Users\\LUMALE~1\\AppData\\Local\\Temp', 'PINGUINO_OS_NAME': 'windows', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'PINGUINO_LIB': 'D:\\Programas\\Pinguino\\v12\\pinguino', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PINGUINO_OS_ARCH': '64bit', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'PINGUINO_PYTHON': '2', 'LOCALAPPDATA': 'C:\\Users\\lumaleo-PC\\AppData\\Local', 'FPS_BROWSER_USER_PROFILE_STRING': 'Default', 'HOMEPATH': '\\Users\\lumaleo-PC', 'USERDOMAIN_ROAMINGPROFILE': 'LUMALEO-PC', 'PINGUINO_VERSION': '12.0.39-beta.2', 'PROGRAMW6432': 'C:\\Program Files', 'USERNAME': 'lumaleo-PC', 'PINGUINO_FULLNAME': 'Pinguino IDE 12.0.39-beta.2', 'LOGONSERVER': '\\\\LUMALEO-PC', 'PROMPT': '$P$G', 'SESSIONNAME': 'Console', 'PROGRAMDATA': 'C:\\ProgramData', 'ONEDRIVE': 'C:\\Users\\lumaleo-PC\\OneDrive', 'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer', 'PINGUINO_MODE': 'NORMAL', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'PINGUINO_DEFAULT_FILES': 'C:\\Users\\lumaleo-PC\\Documents\\Pinguino\\v12\\local', 'JD2_HOME': 'C:\\Users\\lumaleo-PC\\AppData\\Local\\JDownloader v2.0', 'WINDIR': 'C:\\WINDOWS', 'APPDATA': 'C:\\Users\\lumaleo-PC\\AppData\\Roaming', 'HOMEDRIVE': 'C:', 'PINGUINO_USERLIBS_PATH': 'C:\\Users\\lumaleo-PC\\Documents\\Pinguino\\v12\\pinguinolibs', 'SYSTEMDRIVE': 'C:', 'PINGUINO_INSTALL_PATH': 'd:\\Programas\\Pinguino\\v12\\', 'NUMBER_OF_PROCESSORS': '4', 'PINGUINO_PROJECT': '', 'PINGUINO_BOARD_ARCH': '8', 'PROCESSOR_LEVEL': '6', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'OS': 'Windows_NT', 'PUBLIC': 'C:\\Users\\Public', 'PINGUINO_CAN_COMPILE': 'True', 'USERPROFILE': 'C:\\Users\\lumaleo-PC'}

**Comment by MefhigosetH** [comment]
Duplicate #108
