### ISSUE TITLE
from .events import PinguinoEvents

### ISSUE THREAD

**Issue by pietrodizinno** [PinguinoIDE/pinguino-ide#83]
the v12 beta 2 show this message and don' start on windows 10

**Comment by pietrodizinno** [comment]
Traceback (most recent call last):
  File "pinguino-ide.py", line 21, in <module>
    from pinguino import pinguino
  File "C:\Pinguino\v12\pinguino\pinguino.py", line 68, in <module>
    from .qtgui.ide.ide import PinguinoIDE
  File "C:\Pinguino\v12\pinguino\qtgui\ide\ide.py", line 13, in <module>
    from .events import PinguinoEvents
ImportError: cannot import name PinguinoEvents
