### ISSUE TITLE
AttributeError: 'Pinguino' object has no attribute '__hex_file__'

### ISSUE THREAD

**Issue by hemangjoshi37a** [PinguinoIDE/pinguino-ide#86]
Please help me solve this error.

Error messsage : 
Traceback (most recent call last):
  File "/opt/pinguino/v12/pinguino/qtgui/ide/methods/decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "/opt/pinguino/v12/pinguino/qtgui/ide/methods/decorators.py", line 25, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "/opt/pinguino/v12/pinguino/qtgui/ide/methods/core.py", line 863, in pinguino_upload
    uploaded, result = self.pinguinoAPI.upload()
  File "/opt/pinguino/v12/pinguino/qtgui/pinguino_core/pinguino.py", line 137, in upload
    data = self.__upload__()
  File "/opt/pinguino/v12/pinguino/qtgui/pinguino_core/pinguino_tools.py", line 289, in __upload__
    hex_file = self.get_hex_file()
  File "/opt/pinguino/v12/pinguino/qtgui/pinguino_core/pinguino_tools.py", line 203, in get_hex_file
    return self.__hex_file__
AttributeError: 'Pinguino' object has no attribute '__hex_file__'

**Comment by MefhigosetH** [comment]
Duplicate #106
