### ISSUE TITLE
Pinguino IDE doesn't upload compiled code (AttributeError: 'module' object has no attribute 'core')

### ISSUE THREAD

**Issue by isidorogv** [PinguinoIDE/pinguino-ide#87]
Traceback (most recent call last):
  File "/opt/pinguino/v12/pinguino/qtgui/ide/methods/decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "/opt/pinguino/v12/pinguino/qtgui/ide/methods/decorators.py", line 25, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "/opt/pinguino/v12/pinguino/qtgui/ide/methods/core.py", line 863, in pinguino_upload
    uploaded, result = self.pinguinoAPI.upload()
  File "/opt/pinguino/v12/pinguino/qtgui/pinguino_core/pinguino.py", line 137, in upload
    data = self.__upload__()
  File "/opt/pinguino/v12/pinguino/qtgui/pinguino_core/pinguino_tools.py", line 297, in __upload__
    result = self.upload_hex()
  File "/opt/pinguino/v12/pinguino/qtgui/pinguino_core/uploader/uploader.py", line 233, in upload_hex
    self.uploader.uploadDevice(self.hex_file, self.board)
  File "/opt/pinguino/v12/pinguino/qtgui/pinguino_core/uploader/uploader32.py", line 847, in uploadDevice
    device = self.getDevice(board)
  File "/opt/pinguino/v12/pinguino/qtgui/pinguino_core/uploader/uploader.py", line 115, in getDevice
    device = usb.core.find(idVendor=board.vendor, idProduct=board.product)
AttributeError: 'module' object has no attribute 'core'

os.uname: ('Linux', 'Tesla', '3.16.0-4-amd64', '#1 SMP Debian 3.16.43-2 (2017-04-30)', 'x86_64')
os.name: posix
os.environ: {'LD_LIBRARY_PATH': '/usr/lib32:/usr/lib:/usr/lib64', 'GLADE_PIXMAP_PATH': ':', 'PINGUINO_USER_PATH': '/home/isidoro/Pinguino/v12', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm/data/isidoro', 'PINGUINO_DEFAULT_FILES': '/home/isidoro/Pinguino/v12/local', 'PINGUINO_NAME': 'Pinguino IDE', 'XDG_CURRENT_DESKTOP': 'XFCE', 'PINGUINO_BOARD_ARCH': '32', 'LOGNAME': 'isidoro', 'XDG_SEAT': 'seat0', 'HOME': '/home/isidoro', 'XDG_VTNR': '7', 'PATH': '/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games', 'DISPLAY': ':0.0', 'XDG_RUNTIME_DIR': '/run/user/1000', 'LANG': 'es_ES.utf8', 'SHELL': '/bin/bash', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'XAUTHORITY': '/home/isidoro/.Xauthority', 'PINGUINO_OS_NAME': 'linux', 'SESSION_MANAGER': 'local/Tesla:@/tmp/.ICE-unix/865,unix/Tesla:/tmp/.ICE-unix/865', 'XDG_DATA_DIRS': '/usr/share/xfce4:/usr/local/share/:/usr/share/:/usr/share', 'PINGUINO_OS_ARCH': '64bit', 'PINGUINO_PROJECT': '', 'PINGUINO_PYTHON': '2', 'GLADE_CATALOG_PATH': ':', 'PINGUINO_VERSION': '12.0.39-beta.2', 'SSH_AGENT_PID': '851', 'PINGUINO_FULLNAME': 'Pinguino IDE 12.0.39-beta.2', 'GLADE_MODULE_PATH': ':', 'PINGUINO_LIB': '/opt/pinguino/v12/pinguino', 'SSH_AUTH_SOCK': '/tmp/ssh-alXZjmNHX9m1/agent.826', 'GDMSESSION': 'lightdm-xsession', 'PINGUINO_MODE': 'NORMAL', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'XDG_SESSION_ID': '1', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-HVZdnEhqFh,guid=7e0c795541855424617a0fb4591c2127', 'DESKTOP_SESSION': 'lightdm-xsession', 'GPG_AGENT_INFO': '/tmp/gpg-VeWUu9/S.gpg-agent:873:1', 'XDG_CONFIG_DIRS': '/etc/xdg', 'PINGUINO_INSTALL_PATH': '/opt/pinguino/v12', 'PINGUINO_USERLIBS_PATH': '/opt/pinguino/v12/pinguinolibs', 'PWD': '/home/isidoro', 'XDG_MENU_PREFIX': 'xfce-', 'PINGUINO_CAN_COMPILE': 'True', 'USER': 'isidoro'}

**Comment by isidorogv** [comment]
I've just solved this issue some minutes ago. Pyusb module have to be updated to its latest version.

For that, just type as root, the following:

`python -m pip install pyusb --update`

and issue solved.
