### ISSUE TITLE
no se

### ISSUE THREAD

**Issue by pacoqwer** [PinguinoIDE/pinguino-ide#89]
Traceback (most recent call last):
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\decorators.py", line 25, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\decorators.py", line 161, in wrapped
    if saved: fn(Pinguino, *args, **kwargs)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\decorators.py", line 174, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\core.py", line 786, in pinguino_compile
    compile_code()
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\core.py", line 765, in <lambda>
    compile_code = lambda :self.pinguinoAPI.compile_file([filename])
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\pinguino.py", line 85, in compile_file
    data = self.verify(file_path)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\pinguino_tools.py", line 225, in verify
    self.set_os_variables()
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\pinguino_tools.py", line 126, in set_os_variables
    self.COMPILER_8BIT = self.glob_path(self.COMPILER_8BIT)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\pinguino_tools.py", line 136, in glob_path
    return dirs[-1]
IndexError: list index out of range

os.name: nt
os.environ: {'TMP': 'C:\\Users\\EQUIPO~1\\AppData\\Local\\Temp', 'COMPUTERNAME': 'EQUIPO9PC-PC', 'PINGUINO_USER_PATH': 'C:\\Users\\Equipo 9PC\\Documents\\Pinguino\\v12', 'USERDOMAIN': 'Equipo9PC-PC', 'UECIDE': 'C:\\Users\\Equipo 9PC\\AppData\\Local\\UECIDE', 'PSMODULEPATH': 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\', 'PINGUINO_NAME': 'Pinguino IDE', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 42 Stepping 7, GenuineIntel', 'PROGRAMFILES': 'C:\\Program Files', 'PROCESSOR_REVISION': '2a07', 'SYSTEMROOT': 'C:\\Windows', 'PATH': 'C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\PROGRA~2\\PICC;C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\;;C:\\Program Files\\Pinguino\\p8\\bin', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'WINDOWS_TRACING_FLAGS': '3', 'TEMP': 'C:\\Users\\EQUIPO~1\\AppData\\Local\\Temp', 'PINGUINO_OS_NAME': 'windows', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'PINGUINO_LIB': 'C:\\Program Files\\Pinguino\\v12\\pinguino', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PINGUINO_OS_ARCH': '64bit', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'PINGUINO_PYTHON': '2', 'LOCALAPPDATA': 'C:\\Users\\Equipo 9PC\\AppData\\Local', 'HOMEPATH': '\\Users\\Equipo 9PC', 'PINGUINO_VERSION': '12.0.39-beta.2', 'PROGRAMW6432': 'C:\\Program Files', 'USERNAME': 'Equipo 9PC', 'PINGUINO_FULLNAME': 'Pinguino IDE 12.0.39-beta.2', 'LOGONSERVER': '\\\\EQUIPO9PC-PC', 'PROMPT': '$P$G', 'SESSIONNAME': 'Console', 'PROGRAMDATA': 'C:\\ProgramData', 'PINGUINO_INSTALL_PATH': 'C:\\Program Files\\Pinguino\\v12\\', 'PINGUINO_MODE': 'NORMAL', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'PINGUINO_PROJECT': '', 'PINGUINO_DEFAULT_FILES': 'C:\\Users\\Equipo 9PC\\Documents\\Pinguino\\v12\\local', 'FP_NO_HOST_CHECK': 'NO', 'WINDIR': 'C:\\Windows', 'WINDOWS_TRACING_LOGFILE': 'C:\\BVTBin\\Tests\\installpackage\\csilogfile.log', 'HOMEDRIVE': 'C:', 'PINGUINO_USERLIBS_PATH': 'C:\\Users\\Equipo 9PC\\Documents\\Pinguino\\v12\\pinguinolibs', 'SYSTEMDRIVE': 'C:', 'PINGUINO_BOARD_ARCH': '8', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'NUMBER_OF_PROCESSORS': '4', 'APPDATA': 'C:\\Users\\Equipo 9PC\\AppData\\Roaming', 'PROCESSOR_LEVEL': '6', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'OS': 'Windows_NT', 'PUBLIC': 'C:\\Users\\Public', 'PINGUINO_CAN_COMPILE': 'True', 'USERPROFILE': 'C:\\Users\\Equipo 9PC'}

**Comment by MefhigosetH** [comment]
Duplicate #101
