### ISSUE TITLE
Running the IDE fails with "No such file or directory"

### ISSUE THREAD

**Issue by nagisa** [PinguinoIDE/pinguino-ide#95]
```
$ python2 pinguino.py 
WARNING:root:gitpython is an optional dependence for Pinguino's Library Manager.
WARNING:root:pysvn is an optional dependence for Pinguino's Library Manager.
WARNING:root:hgapi is an optional dependence for Pinguino's Library Manager.
WARNING:root:bs4 is an optional dependence for Pinguino's Wiki Libraries.
WARNING:root:Missing Pinguino libraries instalation. Make sure the paths in /tmp/pinguino-ide/paths.conf are correct.
Traceback (most recent call last):
  File "pinguino.py", line 194, in <module>
    frame = PinguinoIDE(splash_write=splash_write, argvs=parser)
  File "/tmp/pinguino-ide/qtgui/ide/ide.py", line 120, in __init__
    self.__update_graphical_path_files__(os.path.join(os.getenv("PINGUINO_USER_PATH"), "graphical_examples"))
  File "/tmp/pinguino-ide/qtgui/ide/methods/methods.py", line 182, in __update_graphical_path_files__
    Files.update_path_files(path, self.main.listWidget_filesg, self.main.label_pathg, exclude=".pde")
  File "/tmp/pinguino-ide/qtgui/ide/tools/files.py", line 17, in update_path_files
    paths = filter(lambda child: not child.startswith("."), os.listdir(path))
OSError: [Errno 2] No such file or directory: '/home/nagisa/Pinguino/v11/examples'

```

**Comment by MefhigosetH** [comment]
v11 not supported now.
