### ISSUE TITLE
NoBackendError: No backend available

### ISSUE THREAD

**Issue by M2701** [PinguinoIDE/pinguino-ide#98]
Traceback (most recent call last):
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\decorators.py", line 25, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\core.py", line 863, in pinguino_upload
    uploaded, result = self.pinguinoAPI.upload()
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\pinguino.py", line 137, in upload
    data = self.__upload__()
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\pinguino_tools.py", line 297, in __upload__
    result = self.upload_hex()
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\uploader\uploader.py", line 233, in upload_hex
    self.uploader.uploadDevice(self.hex_file, self.board)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\uploader\uploader32.py", line 847, in uploadDevice
    device = self.getDevice(board)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\uploader\uploader.py", line 115, in getDevice
    device = usb.core.find(idVendor=board.vendor, idProduct=board.product)
  File "C:\Python27\lib\site-packages\usb\core.py", line 1263, in find
    raise NoBackendError('No backend available')
NoBackendError: No backend available

os.name: nt
os.environ: {'TMP': 'C:\\Users\\M\\AppData\\Local\\Temp', 'COMPUTERNAME': 'OFFICENEW', 'PINGUINO_USER_PATH': 'C:\\Users\\M\\Documents\\Pinguino\\v12', 'USERDOMAIN': 'OFFICENEW', 'PSMODULEPATH': 'C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules\\', 'PINGUINO_NAME': 'Pinguino IDE', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel', 'PROGRAMFILES': 'C:\\Program Files', 'PROCESSOR_REVISION': '3a09', 'SYSTEMROOT': 'C:\\WINDOWS', 'PATH': 'C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\OpenCL SDK\\2.0\\bin\\x86;C:\\Program Files (x86)\\Intel\\OpenCL SDK\\2.0\\bin\\x64;C:\\Program Files (x86)\\Microchip\\xc8\\v1.41\\bin;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Users\\M\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files (x86)\\EaseUS\\Todo Backup\\bin\\x64\\;C:\\Program Files\\Pinguino\\p8\\bin', 'PINGUINO_OS_ARCH': '64bit', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'KICAD_SYMBOL_DIR': 'C:\\Program Files\\KiCad\\share\\kicad\\library', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'KICAD BOM': 'C:\\Users\\M\\Documents\\KiCad Omega\\KicadBOM', 'KISYS3DMOD': 'C:\\Program Files\\KiCad\\share\\kicad\\modules\\packages3d', 'TEMP': 'C:\\Users\\M\\AppData\\Local\\Temp', 'PINGUINO_OS_NAME': 'windows', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'PINGUINO_LIB': 'C:\\Program Files\\Pinguino\\v12\\pinguino', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'KICAD_PTEMPLATES': 'C:\\Program Files\\KiCad\\share\\kicad\\template', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'PINGUINO_PYTHON': '2', 'LOCALAPPDATA': 'C:\\Users\\M\\AppData\\Local', 'HOMEPATH': '\\Users\\M', 'USERDOMAIN_ROAMINGPROFILE': 'OFFICENEW', 'PINGUINO_VERSION': '12.0.39-beta.2', 'PROGRAMW6432': 'C:\\Program Files', 'USERNAME': 'M', 'PINGUINO_FULLNAME': 'Pinguino IDE 12.0.39-beta.2', 'LOGONSERVER': '\\\\OFFICENEW', 'PROMPT': '$P$G', 'SESSIONNAME': 'Console', 'PROGRAMDATA': 'C:\\ProgramData', 'ONEDRIVE': 'C:\\Users\\M\\OneDrive', 'PINGUINO_MODE': 'NORMAL', 'PINGUINO_DEFAULT_FILES': 'C:\\Users\\M\\Documents\\Pinguino\\v12\\local', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'KISYSMOD': 'C:\\Program Files\\KiCad\\share\\kicad\\modules', 'FP_NO_HOST_CHECK': 'NO', 'WINDIR': 'C:\\WINDOWS', 'APPDATA': 'C:\\Users\\M\\AppData\\Roaming', 'HOMEDRIVE': 'C:', 'PINGUINO_USERLIBS_PATH': 'C:\\Users\\M\\Documents\\Pinguino\\v12\\pinguinolibs', 'SYSTEMDRIVE': 'C:', 'PINGUINO_INSTALL_PATH': 'C:\\Program Files\\Pinguino\\v12\\', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'NUMBER_OF_PROCESSORS': '4', 'PINGUINO_PROJECT': '', 'PINGUINO_BOARD_ARCH': '32', 'PROCESSOR_LEVEL': '6', 'MCC_INCLUDE': 'C:\\Program Files (x86)\\Microchip\\xc8\\v1.41/h', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'OS': 'Windows_NT', 'PUBLIC': 'C:\\Users\\Public', 'PINGUINO_CAN_COMPILE': 'True', 'USERPROFILE': 'C:\\Users\\M'}

**Comment by M2701** [comment]
I think things went wrong with a Python update. Have completely uninstalled Pinguino IDE and Python, removed all references on disks, and reinstalled IDE from web, clean copy. Set the USB to 04D8:003C as instructed with Pinguino Micro plugged in and in upload mode. Compiles blinking led to test it out, and this error comes up when upload selected...

**Comment by M2701** [comment]
Is this part of the issue:
Execute: "C:\Python27\python" "C:\Program Files\Pinguino\v12\pinguino\pinguino_reset.py"
Post-installation failed. Error code was: 1!
